train:
  - /gt1205_dataset/dataset/toyoko-03_fix_fixed.csv
  - /gt1205_dataset/dataset/toyoko-05_fixed.csv
  - /gt1205_dataset/dataset/toyoko-09_fix_fixed.csv
  - /gt1205_dataset/dataset/toyoko-10_fix_fixed.csv
  - /gt1205_dataset/dataset/toyoko-11_fix_fixed.csv
  - /gt1205_dataset/dataset/toyoko-12_fix_fixed.csv
  - /gt1205_dataset/dataset/toyoko-22_fixed.csv
  - /gt1205_dataset/dataset/toyoko-23_fixed.csv
  - /gt1205_dataset/dataset/toyoko-13_fix_fixed.csv
  - /gt1205_dataset/dataset/toyoko-16_fix_fixed.csv
  - /gt1205_dataset/dataset/toyoko-24_fixed.csv
  - /gt1205_dataset/dataset/toyoko-19_fix_fixed.csv
  - /topcon_dataset/topcon-aichi-1-f_inertial_aggmr_1_changed.csv
  - /topcon_dataset/topcon-aichi-2-f_inertial_aggmr_1_changed.csv
  - /topcon_dataset/topcon-aichi-3-f_inertial_aggmr_1_changed.csv
  - /topcon_dataset/topcon-aichi-4-f_inertial_aggmr_1_changed.csv
  - /topcon_dataset/topcon-kohama-1-f_inertial_aggmr_1_changed.csv
  - /topcon_dataset/topcon-kohama-2-f_inertial_aggmr_1_changed.csv
  - /topcon_dataset/topcon-kohama-3-f_inertial_aggmr_1_changed.csv
  - /topcon_dataset/topcon-kohama-4-f_inertial_aggmr_1_changed.csv
  - /topcon_dataset/topcon-yoshiki-1-f_inertial_aggmr_1_changed.csv
  - /topcon_dataset/topcon-yoshiki-2-f_inertial_aggmr_1_changed.csv
  - /topcon_dataset/topcon-yoshiki-3-f_inertial_aggmr_1_changed.csv
  - /topcon_dataset/topcon-yoshiki-4-f_inertial_aggmr_1_changed.csv
  - /topcon_dataset/topcon-naot-1-f_inertial_aggmr_1_changed.csv
  - /topcon_dataset/topcon-naot-2-f_inertial_aggmr_1_changed.csv
  - /topcon_dataset/topcon-naot-3-f_inertial_aggmr_1_changed.csv
  - /topcon_dataset/topcon-naot-4-f_inertial_aggmr_1_changed.csv
  - /topcon_dataset/topcon-aichi-1-f_inertial_aggmr_4_changed.csv
  - /topcon_dataset/topcon-aichi-2-f_inertial_aggmr_4_changed.csv
  - /topcon_dataset/topcon-aichi-3-f_inertial_aggmr_4_changed.csv
  - /topcon_dataset/topcon-aichi-4-f_inertial_aggmr_4_changed.csv
  - /topcon_dataset/topcon-kohama-1-f_inertial_aggmr_4_changed.csv
  - /topcon_dataset/topcon-kohama-2-f_inertial_aggmr_4_changed.csv
  - /topcon_dataset/topcon-kohama-3-f_inertial_aggmr_4_changed.csv
  - /topcon_dataset/topcon-kohama-4-f_inertial_aggmr_4_changed.csv
  - /topcon_dataset/topcon-yoshiki-1-f_inertial_aggmr_4_changed.csv
  - /topcon_dataset/topcon-yoshiki-2-f_inertial_aggmr_4_changed.csv
  - /topcon_dataset/topcon-yoshiki-3-f_inertial_aggmr_4_changed.csv
  - /topcon_dataset/topcon-yoshiki-4-f_inertial_aggmr_4_changed.csv
  - /topcon_dataset/topcon-naot-1-f_inertial_aggmr_4_changed.csv
  - /topcon_dataset/topcon-naot-2-f_inertial_aggmr_4_changed.csv
  - /topcon_dataset/topcon-naot-3-f_inertial_aggmr_4_changed.csv
  - /topcon_dataset/topcon-naot-4-f_inertial_aggmr_4_changed.csv
  - /topcon_dataset/topcon-aichi-1-f_inertial_aggmr_5_changed.csv
  - /topcon_dataset/topcon-aichi-2-f_inertial_aggmr_5_changed.csv
  - /topcon_dataset/topcon-aichi-3-f_inertial_aggmr_5_changed.csv
  - /topcon_dataset/topcon-aichi-4-f_inertial_aggmr_5_changed.csv
  - /topcon_dataset/topcon-kohama-1-f_inertial_aggmr_5_changed.csv
  - /topcon_dataset/topcon-kohama-2-f_inertial_aggmr_5_changed.csv
  - /topcon_dataset/topcon-kohama-3-f_inertial_aggmr_5_changed.csv
  - /topcon_dataset/topcon-kohama-4-f_inertial_aggmr_5_changed.csv
  - /topcon_dataset/topcon-yoshiki-1-f_inertial_aggmr_5_changed.csv
  - /topcon_dataset/topcon-yoshiki-2-f_inertial_aggmr_5_changed.csv
  - /topcon_dataset/topcon-yoshiki-3-f_inertial_aggmr_5_changed.csv
  - /topcon_dataset/topcon-yoshiki-4-f_inertial_aggmr_5_changed.csv
  - /topcon_dataset/topcon-naot-1-f_inertial_aggmr_5_changed.csv
  - /topcon_dataset/topcon-naot-2-f_inertial_aggmr_5_changed.csv
  - /topcon_dataset/topcon-naot-3-f_inertial_aggmr_5_changed.csv
  - /topcon_dataset/topcon-naot-4-f_inertial_aggmr_5_changed.csv

validate:
  - /gt1205_dataset/dataset/toyoko-04_fix_fixed.csv
  - /gt1205_dataset/dataset/toyoko-06_fix_fixed.csv
  - /gt1205_dataset/dataset/toyoko-14_fix_fixed.csv
  - /gt1205_dataset/dataset/toyoko-17_fix_fixed.csv
  - /gt1205_dataset/dataset/toyoko-20_fix_fixed.csv
  - /topcon_dataset/topcon-aichi-1-f_inertial_aggmr_2_changed.csv
  - /topcon_dataset/topcon-aichi-2-f_inertial_aggmr_2_changed.csv
  - /topcon_dataset/topcon-aichi-3-f_inertial_aggmr_2_changed.csv
  - /topcon_dataset/topcon-aichi-4-f_inertial_aggmr_2_changed.csv
  - /topcon_dataset/topcon-kohama-1-f_inertial_aggmr_2_changed.csv
  - /topcon_dataset/topcon-kohama-2-f_inertial_aggmr_2_changed.csv
  - /topcon_dataset/topcon-kohama-3-f_inertial_aggmr_2_changed.csv
  - /topcon_dataset/topcon-kohama-4-f_inertial_aggmr_2_changed.csv
  - /topcon_dataset/topcon-yoshiki-1-f_inertial_aggmr_2_changed.csv
  - /topcon_dataset/topcon-yoshiki-2-f_inertial_aggmr_2_changed.csv
  - /topcon_dataset/topcon-yoshiki-3-f_inertial_aggmr_2_changed.csv
  - /topcon_dataset/topcon-yoshiki-4-f_inertial_aggmr_2_changed.csv
  - /topcon_dataset/topcon-naot-1-f_inertial_aggmr_2_changed.csv
  - /topcon_dataset/topcon-naot-2-f_inertial_aggmr_2_changed.csv
  - /topcon_dataset/topcon-naot-3-f_inertial_aggmr_2_changed.csv
  - /topcon_dataset/topcon-naot-4-f_inertial_aggmr_2_changed.csv

test:
  - /gt1205_dataset/dataset/toyoko-07_fix_fixed.csv
  - /gt1205_dataset/dataset/toyoko-08_fix_fixed.csv
  - /gt1205_dataset/dataset/toyoko-15_fix_fixed.csv
  - /gt1205_dataset/dataset/toyoko-18_fix_fixed.csv
  - /gt1205_dataset/dataset/toyoko-21_fix_fixed.csv
  - /topcon_dataset/topcon-aichi-1-f_inertial_aggmr_3_changed.csv
  - /topcon_dataset/topcon-aichi-2-f_inertial_aggmr_3_changed.csv
  - /topcon_dataset/topcon-aichi-3-f_inertial_aggmr_3_changed.csv
  - /topcon_dataset/topcon-aichi-4-f_inertial_aggmr_3_changed.csv
  - /topcon_dataset/topcon-kohama-1-f_inertial_aggmr_3_changed.csv
  - /topcon_dataset/topcon-kohama-2-f_inertial_aggmr_3_changed.csv
  - /topcon_dataset/topcon-kohama-3-f_inertial_aggmr_3_changed.csv
  - /topcon_dataset/topcon-kohama-4-f_inertial_aggmr_3_changed.csv
  - /topcon_dataset/topcon-yoshiki-1-f_inertial_aggmr_3_changed.csv
  - /topcon_dataset/topcon-yoshiki-2-f_inertial_aggmr_3_changed.csv
  - /topcon_dataset/topcon-yoshiki-3-f_inertial_aggmr_3_changed.csv
  - /topcon_dataset/topcon-yoshiki-4-f_inertial_aggmr_3_changed.csv
  - /topcon_dataset/topcon-naot-1-f_inertial_aggmr_3_changed.csv
  - /topcon_dataset/topcon-naot-2-f_inertial_aggmr_3_changed.csv
  - /topcon_dataset/topcon-naot-3-f_inertial_aggmr_3_changed.csv
  - /topcon_dataset/topcon-naot-4-f_inertial_aggmr_3_changed.csv
